{
 "title": "Cert-Monitoring",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Expiration within half year",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 8, "x": 0, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "(count(cert_exporter_cert_expires_in_seconds <= 15724800) OR on() vector(0)) +\n(count(cert_exporter_kubeconfig_expires_in_seconds <= 15724800) OR on() vector(0)) +\n(count(cert_exporter_secret_expires_in_seconds <= 15724800) OR on() vector(0))"
    }
   ]
  },
  {
   "title": "Expiration within half and one year",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 8, "x": 8, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "(count(15724800 < cert_exporter_cert_expires_in_seconds and cert_exporter_cert_expires_in_seconds <= 31536000) OR on() vector(0)) +\n(count(15724800 < cert_exporter_kubeconfig_expires_in_seconds and cert_exporter_kubeconfig_expires_in_seconds <= 31536000) OR on() vector(0)) +\n(count(15724800 < cert_exporter_secret_expires_in_seconds and cert_exporter_secret_expires_in_seconds <= 31536000) OR on() vector(0))"
    }
   ]
  },
  {
   "title": "Expiration after one year",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 8, "x": 16, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "(count(cert_exporter_cert_expires_in_seconds > 31536000) OR on() vector(0)) +\n(count(cert_exporter_kubeconfig_expires_in_seconds > 31536000) OR on() vector(0)) +\n(count(cert_exporter_secret_expires_in_seconds > 31536000) OR on() vector(0))"
    }
   ]
  },
  {
   "title": "Errors Total",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 5, "x": 0, "y": 2 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    { "expr": "sum(cert_exporter_error_total)" }
   ]
  },
  {
   "title": "Errors [1h]",
   "type": "graph",
   "gridPos": { "h": 6, "w": 19, "x": 5, "y": 2 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "increase(cert_exporter_error_total[1h])",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Kubernetes and Etcd PKI Cert Expiry",
   "type": "table-old",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "cert_exporter_cert_expires_in_seconds"
    }
   ]
  },
  {
   "title": "Kubeconfig Cert Expiry",
   "type": "table-old",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "cert_exporter_kubeconfig_expires_in_seconds"
    }
   ]
  }
 ]
}